[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FD1150>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d3054ea9eac7175435968faf69f5f1ae
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FD0590>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d3054ea9eac7175435968faf69f5f1ae
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001F7C5FC1410>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/d3054ea9eac7175435968faf69f5f1ae