[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B55F0F0310>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/60f46a71928b3267a97dd5b87a673a45
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B55F0F0A90>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/60f46a71928b3267a97dd5b87a673a45
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001B55F0F12D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/60f46a71928b3267a97dd5b87a673a45