[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021854A60E50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/deac81ffd3b1bbe4751b73b7d0b17482
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021854A60D50>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/deac81ffd3b1bbe4751b73b7d0b17482
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:871 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000021854A62DD0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/deac81ffd3b1bbe4751b73b7d0b17482